// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.example.topake.dagger2kotlinsample.di;

import android.app.Application;
import dagger.internal.MembersInjectors;
import dagger.internal.Preconditions;

public final class DaggerAppComponentKotlin implements AppComponentKotlin {
  private DaggerAppComponentKotlin(Builder builder) {
    assert builder != null;
  }

  public static AppComponentKotlin.Builder builder() {
    return new Builder();
  }

  @Override
  public void inject(Application p0) {
    MembersInjectors.<Application>noOp().injectMembers(p0);
  }

  private static final class Builder implements AppComponentKotlin.Builder {
    private Application application;

    @Override
    public AppComponentKotlin build() {
      if (application == null) {
        throw new IllegalStateException(Application.class.getCanonicalName() + " must be set");
      }
      return new DaggerAppComponentKotlin(this);
    }

    @Override
    public Builder application(Application p0) {
      this.application = Preconditions.checkNotNull(p0);
      return this;
    }
  }
}
